name: gsheet_to_arb
version: 0.1.11
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dart_style: ^2.0.0
  intl: ^0.17.0
  path: ^1.8.0
  googleapis_auth: ^1.1.0
  googleapis: ^2.0.0
  code_builder: ^4.0.0
  intl_translation:
    git: https://github.com/mrbigcho/intl_translation.git
  json_annotation: ^4.0.1
  file_utils: ^1.0.0
  logging: ^1.0.1
  recase: ^4.0.0
  quiver: ^3.0.1
  yaml: ^3.1.0
  petitparser: ^4.1.0

dev_dependencies:
  analyzer: ^1.5.0
  test: ^1.17.1
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  pedantic: ^1.11.0
